language: perl
perl:
  - "5.10"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

before_install:
  - cpanm Carton
install:
  - carton install
script:
  - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" carton exec prove -lrv t

after_success:
  - carton exec -- cover -report coveralls

notifications:
  emails:
    - mihyaeru21@gmail.com
  on_success: always
  on_failure: always

